In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
Path = '/content/drive/MyDrive/retail_transactions.'

In [ ]:
df = pd.read_csv(Path)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
from datetime import datetime

In [ ]:
df['TransactionDate']=pd.to_datetime(df['TransactionDate'])

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
df.head(15)

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,NaN
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
5,T006,2024-01-06,103,1836,515,Grocery,9,227,Debit,NaN
6,T007,2024-01-07,103,1983,586,Electronics,1,170,Credit,NaN
7,T008,2024-01-08,101,1806,569,Toys,4,500,Debit,0.0
8,T009,2024-01-09,101,1925,548,Apparel,7,217,Cash,10.0
9,T010,2024-01-10,101,1711,565,Furniture,3,466,Debit,5.0
10,T011,2024-01-11,103,1276,565,Furniture,1,321,Cash,NaN
11,T012,2024-01-12,101,1486,523,Toys,8,426,Credit,5.0
12,T013,2024-01-13,103,1597,516,Toys,5,262,Cash,15.0
13,T014,2024-01-14,101,1462,520,Electronics,10,218,Cash,NaN
14,T015,2024-01-15,104,1668,581,Toys,4,201,Debit,15.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    100 non-null    object
 1   TransactionDate  100 non-null    datetime64[ns]
 2   StoreID          100 non-null    int64
 3   CustomerID       100 non-null    int64
 4   ProductID        100 non-null    int64
 5   ProductCategory  100 non-null    object
 6   Quantity         100 non-null    int64
 7   Price            100 non-null    int64
 8   PaymentType      100 non-null    object
 9   Discount         75 non-null     float64
dtypes: datetime64[ns](1), float64(1), int64(5), object(3)
memory usage: 7.9+ KB

In [ ]:
df.describe()

,TransactionDate,StoreID,CustomerID,ProductID,Quantity,Price,Discount
count,100,100.000000,100.000000,100.000000,100.000000,100.00000,75.000000
mean,2024-02-19 12:00:00,102.730000,1552.520000,554.390000,5.370000,282.15000,7.733333
min,2024-01-01 00:00:00,101.000000,1013.000000,501.000000,1.000000,50.00000,0.000000
25%,2024-01-25 18:00:00,101.000000,1310.250000,529.750000,3.000000,165.75000,2.500000
50%,2024-02-19 12:00:00,103.000000,1534.000000,554.000000,5.500000,280.00000,10.000000
75%,2024-03-15 06:00:00,104.000000,1800.750000,579.500000,8.000000,415.25000,12.500000
max,2024-04-09 00:00:00,105.000000,1983.000000,600.000000,10.000000,500.00000,15.000000
std,NaN,1.384291,268.295461,28.544098,3.013957,140.19938,5.652871

In [ ]:
df.isnull().sum()

TransactionID       0
TransactionDate     0
StoreID             0
CustomerID          0
ProductID           0
ProductCategory     0
Quantity            0
Price               0
PaymentType         0
Discount           25
dtype: int64

In [ ]:
df['Quantity']=pd.to_numeric(df['Quantity'])
df['Price']=pd.to_numeric(df['Price'])
df['Discount']=pd.to_numeric(df['Discount'])

df['Discount']= df['Discount'].fillna(0)

In [ ]:
df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0
...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0

In [ ]:
df['NetPrice'] = df['Price'] * (1 - df['Discount'] / 100)

In [ ]:
df['NetPrice']

0     127.50
1     285.30
2     165.00
3     446.40
4     166.00
       ...
95    395.10
96     52.00
97    135.90
98    431.10
99    209.95
Name: NetPrice, Length: 100, dtype: float64

In [ ]:
df['TotalSale'] = df['Quantity'] * df['NetPrice']

In [ ]:
df['TotalSale']

0      127.50
1      570.60
2      825.00
3     2678.40
4     1660.00
       ...
95     790.20
96     208.00
97     951.30
98    2155.50
99    1049.75
Name: TotalSale, Length: 100, dtype: float64

In [ ]:
filtered_df = df[df['TotalSale'] >= 20]

In [ ]:
filtered_df

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.50
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.60
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.00
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.40
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.00
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,790.20
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,208.00
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,951.30
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,2155.50
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,1049.75

In [ ]:
df1 = filtered_df

In [ ]:
df1

,TransactionID,TransactionDate,StoreID,CustomerID,ProductID,ProductCategory,Quantity,Price,PaymentType,Discount,NetPrice,TotalSale
0,T001,2024-01-01,102,1646,545,Electronics,1,150,Credit,15.0,127.50,127.50
1,T002,2024-01-02,103,1226,542,Toys,2,317,Debit,10.0,285.30,570.60
2,T003,2024-01-03,102,1515,593,Electronics,5,165,Debit,0.0,165.00,825.00
3,T004,2024-01-04,103,1793,560,Furniture,6,496,Debit,10.0,446.40,2678.40
4,T005,2024-01-05,105,1864,523,Grocery,10,166,Debit,0.0,166.00,1660.00
...,...,...,...,...,...,...,...,...,...,...,...,...
95,T096,2024-04-05,101,1918,559,Apparel,2,439,Cash,10.0,395.10,790.20
96,T097,2024-04-06,104,1190,579,Electronics,4,52,Debit,0.0,52.00,208.00
97,T098,2024-04-07,102,1932,504,Apparel,7,151,Credit,10.0,135.90,951.30
98,T099,2024-04-08,103,1285,587,Apparel,5,479,Credit,10.0,431.10,2155.50
99,T100,2024-04-09,101,1602,574,Electronics,5,247,Credit,15.0,209.95,1049.75

In [ ]:
df['PaymentType']= df['PaymentType'].astype('category')

In [ ]:
df['PaymentType']

0     Credit
1      Debit
2      Debit
3      Debit
4      Debit
       ...
95      Cash
96     Debit
97    Credit
98    Credit
99    Credit
Name: PaymentType, Length: 100, dtype: category
Categories (3, object): ['Cash', 'Credit', 'Debit']

In [ ]:
grouped_df = df1.groupby('ProductCategory').sum().reset_index()

TypeError: datetime64 type does not support sum operations

In [ ]:
grouped_df